---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

environments:
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

---
grails:
    profile: rest-api
    codegen:
        defaultPackage: com.rackspace.vdo.config
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
grails:
    plugin:
        springsecurity:
            userDetailsServiceBeanClass: com.rackspace.vdo.config.UserDetailsService
            globalAuth:
                allowAuthToken: true
            providerNames:
            -   anonymousAuthenticationProvider
            -   globalAuthProvider
            userLookup:
                userDomainClassName: com.rackspace.vdo.config.User
                authorityJoinClassName: com.rackspace.vdo.config.UserRole
                groupJoinClassName: com.rackspace.vdo.config.UserGroup
            groups:
                groupDomainClassName: com.rackspace.vdo.config.Group
                groupNamePropertyName: name
            authority:
                className: com.rackspace.vdo.config.Role
                groupAuthorityNameField: authorities
            useRoleGroups: true
            controllerAnnotations:
                staticRules:
                -   pattern: /
                    access:
                    -   permitAll
                -   pattern: /error
                    access:
                    -   permitAll
                -   pattern: /index
                    access:
                    -   permitAll
                -   pattern: /index.gsp
                    access:
                    -   permitAll
                -   pattern: /shutdown
                    access:
                    -   permitAll
                -   pattern: /assets/**
                    access:
                    -   permitAll
                -   pattern: /**/js/**
                    access:
                    -   permitAll
                -   pattern: /**/css/**
                    access:
                    - permitAll
                -   pattern: /**/images/**
                    access:
                    -   permitAll
                -   pattern: /**/favicon.ico
                    access:
                    -   permitAll

            filterChain:
                chainMap:
                -   pattern: /assets/**
                    filters: none
                -   pattern: /**/js/**
                    filters: none
                -   pattern: /**/css/**
                    filters: none
                -   pattern: /**/images/**
                    filters: none
                -   pattern: /**/favicon.ico
                    filters: none
                -   pattern: /**
                    filters: JOINED_FILTERS

            roleHierarchy: |
                ROLE_MODIFY > ROLE_VIEW
